//@GeneratedCode
namespace QTTaxiDriver.WebApi.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class DriverEdit
    {
        ///
        /// Generated by the generator
        ///
        static DriverEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public DriverEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String Name { get; set; } = string.Empty;
    }
}
