//@GeneratedCode
namespace QTTaxiDriver.WebApi.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Vehicle
    {
        ///
        /// Generated by the generator
        ///
        static Vehicle()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Vehicle()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public IdType CompanyId { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.DateTime ApprovalDate { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.String Brand { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.String Model { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public QTTaxiDriver.Logic.Modules.Common.VehicleType Type { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.String LicensePlate { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.Int32 Mileage { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public QTTaxiDriver.WebApi.Models.Base.Company? Company { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Collections.Generic.List<QTTaxiDriver.WebApi.Models.Base.Driver> Drivers { get; set; } = new();
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.WebApi.Models.Base.Vehicle Create()
        {
            BeforeCreate();
            var result = new QTTaxiDriver.WebApi.Models.Base.Vehicle();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.WebApi.Models.Base.Vehicle Create(object other)
        {
            BeforeCreate(other);
            var result = new QTTaxiDriver.WebApi.Models.Base.Vehicle();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTTaxiDriver.WebApi.Models.Base.Vehicle instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTTaxiDriver.WebApi.Models.Base.Vehicle instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.WebApi.Models.Base.Vehicle Create(QTTaxiDriver.Logic.Models.Base.Vehicle other)
        {
            BeforeCreate(other);
            var result = new QTTaxiDriver.WebApi.Models.Base.Vehicle();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTTaxiDriver.Logic.Models.Base.Vehicle other);
        static partial void AfterCreate(QTTaxiDriver.WebApi.Models.Base.Vehicle instance, QTTaxiDriver.Logic.Models.Base.Vehicle other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTTaxiDriver.Logic.Models.Base.Vehicle other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                CompanyId = other.CompanyId;
                ApprovalDate = other.ApprovalDate;
                Brand = other.Brand;
                Model = other.Model;
                Type = other.Type;
                LicensePlate = other.LicensePlate;
                Mileage = other.Mileage;
                Company = other.Company != null ? QTTaxiDriver.WebApi.Models.Base.Company.Create((object)other.Company) : null;
                Drivers = other.Drivers.Select(e => QTTaxiDriver.WebApi.Models.Base.Driver.Create((object)e)).ToList();
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTTaxiDriver.Logic.Models.Base.Vehicle other, ref bool handled);
        partial void AfterCopyProperties(QTTaxiDriver.Logic.Models.Base.Vehicle other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTTaxiDriver.WebApi.Models.Base.Vehicle other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                CompanyId = other.CompanyId;
                ApprovalDate = other.ApprovalDate;
                Brand = other.Brand;
                Model = other.Model;
                Type = other.Type;
                LicensePlate = other.LicensePlate;
                Mileage = other.Mileage;
                Company = other.Company != null ? QTTaxiDriver.WebApi.Models.Base.Company.Create((object)other.Company) : null;
                Drivers = other.Drivers.Select(e => QTTaxiDriver.WebApi.Models.Base.Driver.Create((object)e)).ToList();
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTTaxiDriver.WebApi.Models.Base.Vehicle other, ref bool handled);
        partial void AfterCopyProperties(QTTaxiDriver.WebApi.Models.Base.Vehicle other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.Vehicle other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(CompanyId, ApprovalDate, Brand, Model, Type, LicensePlate, Mileage, Company, Drivers, Id);
        }
    }
}
