//@GeneratedCode
namespace QTTaxiDriver.Logic.Models.Base
{
    ///
    /// Generated by the generator
    ///
    public partial class Driver
    {
        ///
        /// Generated by the generator
        ///
        static Driver()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Driver()
        {
            Constructing();
            _source = new Entities.Base.Driver();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        internal Driver(Entities.Base.Driver source)
        {
            Constructing();
            _source = source;
            Constructed();
        }
        
        new internal Entities.Base.Driver Source
        {
            get => (Entities.Base.Driver)(_source!);
            set => _source = value;
        }
        
        public System.String Name
        {
            get => Source.Name;
            set => Source.Name = value;
        }
        
        private CommonBase.Modules.Collection.DelegateList<QTTaxiDriver.Logic.Entities.Base.Vehicle, QTTaxiDriver.Logic.Models.Base.Vehicle>? _vehicles;
        public System.Collections.Generic.IList<QTTaxiDriver.Logic.Models.Base.Vehicle> Vehicles
        {
            get => _vehicles ??= new CommonBase.Modules.Collection.DelegateList<QTTaxiDriver.Logic.Entities.Base.Vehicle, QTTaxiDriver.Logic.Models.Base.Vehicle>(Source.Vehicles, e => QTTaxiDriver.Logic.Models.Base.Vehicle.Create(e));
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(Entities.Base.Driver other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Name = other.Name;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(Entities.Base.Driver other, ref bool handled);
        partial void AfterCopyProperties(Entities.Base.Driver other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTTaxiDriver.Logic.Models.Base.Driver other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Name = other.Name;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTTaxiDriver.Logic.Models.Base.Driver other, ref bool handled);
        partial void AfterCopyProperties(QTTaxiDriver.Logic.Models.Base.Driver other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.Driver other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Name, Vehicles, Id);
        }
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.Logic.Models.Base.Driver Create()
        {
            BeforeCreate();
            var result = new QTTaxiDriver.Logic.Models.Base.Driver();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.Logic.Models.Base.Driver Create(object other)
        {
            BeforeCreate(other);
            var result = new QTTaxiDriver.Logic.Models.Base.Driver();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.Logic.Models.Base.Driver Create(QTTaxiDriver.Logic.Models.Base.Driver other)
        {
            BeforeCreate(other);
            var result = new QTTaxiDriver.Logic.Models.Base.Driver();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.Logic.Models.Base.Driver Create(Entities.Base.Driver other)
        {
            BeforeCreate(other);
            var result = new QTTaxiDriver.Logic.Models.Base.Driver();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTTaxiDriver.Logic.Models.Base.Driver instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTTaxiDriver.Logic.Models.Base.Driver instance, object other);
        static partial void BeforeCreate(QTTaxiDriver.Logic.Models.Base.Driver other);
        static partial void AfterCreate(QTTaxiDriver.Logic.Models.Base.Driver instance, QTTaxiDriver.Logic.Models.Base.Driver other);
        static partial void BeforeCreate(Entities.Base.Driver other);
        static partial void AfterCreate(QTTaxiDriver.Logic.Models.Base.Driver instance, Entities.Base.Driver other);
    }
}
