//@GeneratedCode
namespace QTTaxiDriver.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class DriveEdit
    {
        ///
        /// Generated by the generator
        ///
        static DriveEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public DriveEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public IdType VehicleId { get; set; }
        ///
        /// Generated by the generator
        ///
        public IdType DriverId { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.DateTime Date { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.Int32 Distance { get; set; }
        ///
        /// Generated by the generator
        ///
        public QTTaxiDriver.WebApi.Models.Base.Driver? Driver { get; set; }
        ///
        /// Generated by the generator
        ///
        public QTTaxiDriver.WebApi.Models.Base.Vehicle? Vehicle { get; set; }
    }
}
