//@GeneratedCode
namespace QTTaxiDriver.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Drive
    {
        ///
        /// Generated by the generator
        ///
        static Drive()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Drive()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public IdType VehicleId { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public IdType DriverId { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.DateTime Date { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Int32 Distance { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public QTTaxiDriver.WebApi.Models.Base.Driver? Driver { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public QTTaxiDriver.WebApi.Models.Base.Vehicle? Vehicle { get; set; }
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.WebApi.Models.App.Drive Create()
        {
            BeforeCreate();
            var result = new QTTaxiDriver.WebApi.Models.App.Drive();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.WebApi.Models.App.Drive Create(object other)
        {
            BeforeCreate(other);
            var result = new QTTaxiDriver.WebApi.Models.App.Drive();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTTaxiDriver.WebApi.Models.App.Drive instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTTaxiDriver.WebApi.Models.App.Drive instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.WebApi.Models.App.Drive Create(QTTaxiDriver.Logic.Models.App.Drive other)
        {
            BeforeCreate(other);
            var result = new QTTaxiDriver.WebApi.Models.App.Drive();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTTaxiDriver.Logic.Models.App.Drive other);
        static partial void AfterCreate(QTTaxiDriver.WebApi.Models.App.Drive instance, QTTaxiDriver.Logic.Models.App.Drive other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTTaxiDriver.Logic.Models.App.Drive other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                VehicleId = other.VehicleId;
                DriverId = other.DriverId;
                Date = other.Date;
                Distance = other.Distance;
                Driver = other.Driver != null ? QTTaxiDriver.WebApi.Models.Base.Driver.Create((object)other.Driver) : null;
                Vehicle = other.Vehicle != null ? QTTaxiDriver.WebApi.Models.Base.Vehicle.Create((object)other.Vehicle) : null;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTTaxiDriver.Logic.Models.App.Drive other, ref bool handled);
        partial void AfterCopyProperties(QTTaxiDriver.Logic.Models.App.Drive other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTTaxiDriver.WebApi.Models.App.Drive other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                VehicleId = other.VehicleId;
                DriverId = other.DriverId;
                Date = other.Date;
                Distance = other.Distance;
                Driver = other.Driver != null ? QTTaxiDriver.WebApi.Models.Base.Driver.Create((object)other.Driver) : null;
                Vehicle = other.Vehicle != null ? QTTaxiDriver.WebApi.Models.Base.Vehicle.Create((object)other.Vehicle) : null;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTTaxiDriver.WebApi.Models.App.Drive other, ref bool handled);
        partial void AfterCopyProperties(QTTaxiDriver.WebApi.Models.App.Drive other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Drive other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(VehicleId, DriverId, Date, Distance, Driver, Vehicle, Id);
        }
    }
}
