//@GeneratedCode
namespace QTTaxiDriver.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class DrivesController : Controllers.GenericController<QTTaxiDriver.Logic.Models.App.Drive, QTTaxiDriver.WebApi.Models.App.DriveEdit, QTTaxiDriver.WebApi.Models.App.Drive>
    {
        ///
        /// Generated by the generator
        ///
        static DrivesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public DrivesController(QTTaxiDriver.Logic.Contracts.App.IDrivesAccess other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTTaxiDriver.WebApi.Models.App.Drive ToOutModel(QTTaxiDriver.Logic.Models.App.Drive accessModel)
        {
            var handled = false;
            var result = default(QTTaxiDriver.WebApi.Models.App.Drive);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTTaxiDriver.WebApi.Models.App.Drive.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTTaxiDriver.Logic.Models.App.Drive accessModel, ref QTTaxiDriver.WebApi.Models.App.Drive? outModel, ref bool handled);
        partial void AfterToOutModel(QTTaxiDriver.WebApi.Models.App.Drive outModel);
    }
}
