//@GeneratedCode
namespace QTTaxiDriver.WebApi
{
    ///
    /// Generated by the generator
    ///
    partial class Program
    {
        static partial void AddServices(WebApplicationBuilder builder)
        {
            builder.Services.AddTransient<QTTaxiDriver.Logic.Contracts.Base.ICompaniesAccess, QTTaxiDriver.Logic.Controllers.Base.CompaniesController>();
            builder.Services.AddTransient<QTTaxiDriver.Logic.Contracts.Base.IDriversAccess, QTTaxiDriver.Logic.Controllers.Base.DriversController>();
            builder.Services.AddTransient<QTTaxiDriver.Logic.Contracts.Base.IVehiclesAccess, QTTaxiDriver.Logic.Controllers.Base.VehiclesController>();
            builder.Services.AddTransient<QTTaxiDriver.Logic.Contracts.App.IDrivesAccess, QTTaxiDriver.Logic.Controllers.App.DrivesController>();
        }
    }
}
