//@GeneratedCode
namespace QTTaxiDriver.Logic.Contracts.Base
{
    using TOutModel = Models.Base.Company;
    ///
    /// Generated by the generator
    ///
    public partial interface ICompaniesAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
