//@GeneratedCode
namespace QTTaxiDriver.Logic.Contracts.Base
{
    using TOutModel = Models.Base.Driver;
    ///
    /// Generated by the generator
    ///
    public partial interface IDriversAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
