//@GeneratedCode
namespace QTTaxiDriver.Logic.Contracts.Base
{
    using TOutModel = Models.Base.Vehicle;
    ///
    /// Generated by the generator
    ///
    public partial interface IVehiclesAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
