//@GeneratedCode
namespace QTTaxiDriver.Logic.Contracts.App
{
    using TOutModel = Models.App.Drive;
    ///
    /// Generated by the generator
    ///
    public partial interface IDrivesAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
