//@GeneratedCode
namespace QTTaxiDriver.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class CompaniesController : Controllers.GenericController<QTTaxiDriver.Logic.Models.Base.Company, QTTaxiDriver.WebApi.Models.Base.CompanyEdit, QTTaxiDriver.WebApi.Models.Base.Company>
    {
        ///
        /// Generated by the generator
        ///
        static CompaniesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public CompaniesController(QTTaxiDriver.Logic.Contracts.Base.ICompaniesAccess other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTTaxiDriver.WebApi.Models.Base.Company ToOutModel(QTTaxiDriver.Logic.Models.Base.Company accessModel)
        {
            var handled = false;
            var result = default(QTTaxiDriver.WebApi.Models.Base.Company);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTTaxiDriver.WebApi.Models.Base.Company.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTTaxiDriver.Logic.Models.Base.Company accessModel, ref QTTaxiDriver.WebApi.Models.Base.Company? outModel, ref bool handled);
        partial void AfterToOutModel(QTTaxiDriver.WebApi.Models.Base.Company outModel);
    }
}
