//@GeneratedCode
namespace QTTaxiDriver.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class DriversController : Controllers.GenericController<QTTaxiDriver.Logic.Models.Base.Driver, QTTaxiDriver.WebApi.Models.Base.DriverEdit, QTTaxiDriver.WebApi.Models.Base.Driver>
    {
        ///
        /// Generated by the generator
        ///
        static DriversController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public DriversController(QTTaxiDriver.Logic.Contracts.Base.IDriversAccess other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTTaxiDriver.WebApi.Models.Base.Driver ToOutModel(QTTaxiDriver.Logic.Models.Base.Driver accessModel)
        {
            var handled = false;
            var result = default(QTTaxiDriver.WebApi.Models.Base.Driver);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTTaxiDriver.WebApi.Models.Base.Driver.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTTaxiDriver.Logic.Models.Base.Driver accessModel, ref QTTaxiDriver.WebApi.Models.Base.Driver? outModel, ref bool handled);
        partial void AfterToOutModel(QTTaxiDriver.WebApi.Models.Base.Driver outModel);
    }
}
