//@GeneratedCode
namespace QTTaxiDriver.MvvMApp.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Vehicle
    {
        ///
        /// Generated by the generator
        ///
        static Vehicle()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Vehicle()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public IdType CompanyId { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.DateTime ApprovalDate { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.String Brand { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.String Model { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public QTTaxiDriver.Logic.Modules.Common.VehicleType Type { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.String LicensePlate { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.Int32 Mileage { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public QTTaxiDriver.MvvMApp.Models.Base.Company? Company { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Collections.Generic.List<QTTaxiDriver.MvvMApp.Models.Base.Driver> Drivers { get; set; } = new();
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.MvvMApp.Models.Base.Vehicle Create()
        {
            BeforeCreate();
            var result = new QTTaxiDriver.MvvMApp.Models.Base.Vehicle();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTTaxiDriver.MvvMApp.Models.Base.Vehicle Create(object other)
        {
            BeforeCreate(other);
            var result = new QTTaxiDriver.MvvMApp.Models.Base.Vehicle();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTTaxiDriver.MvvMApp.Models.Base.Vehicle instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTTaxiDriver.MvvMApp.Models.Base.Vehicle instance, object other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.Vehicle other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(CompanyId, ApprovalDate, Brand, Model, Type, LicensePlate, Mileage, Company, Drivers, Id);
        }
    }
}
