//@GeneratedCode
namespace QTTaxiDriver.Logic.DataContext
{
    ///
    /// Generated by the generator
    ///
    partial class ProjectDbContext
    {
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.Base.Company>? CompanySet{ get; set; }
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.Base.Driver>? DriverSet{ get; set; }
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.Base.Vehicle>? VehicleSet{ get; set; }
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.App.Drive>? DriveSet{ get; set; }
        
        ///
        /// Generated by the generator
        ///
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.EntityObject
        {
            if (typeof(E) == typeof(Entities.Base.Company))
            {
                dbSet = CompanySet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Base.Driver))
            {
                dbSet = DriverSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Base.Vehicle))
            {
                dbSet = VehicleSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.Drive))
            {
                dbSet = DriveSet as DbSet<E>;
                handled = true;
            }
        }
    }
}
